### ISSUE TITLE
error by executing binary-data-commands-and-heartbeats-via-mqtt.py

### ISSUE THREAD

**Issue by fableh** [SAP/iot-starterkit#66]
Hi all,

i just tried out the above menbtioned python script.
but in this line:

`client.tls_set(config_crt_4_landscape, certfile=config_credentials_crt, keyfile=config_credentials_key)`

I got this result:
```
Traceback (most recent call last):
  File "commands_and_heartbeat.py", line 101, in <module>
    client.connect(broker, broker_port, 60)
  File "E:\python363\lib\site-packages\paho\mqtt\client.py", line 768, in connect
    return self.reconnect()
  File "E:\python363\lib\site-packages\paho\mqtt\client.py", line 927, in reconnect
    sock.do_handshake()
  File "E:\python363\lib\ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "E:\python363\lib\ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)
```
If i change the line to:

`client.tls_set(ca_certs=None ,certfile=config_credentials_crt,  keyfile=config_credentials_key)`

it works:
(0, 2)
Connected to MQTT broker with result code: 0
on_subscribe - message_id: 1 / qos: (0,)

the provided iot service cert "config_crt_4_landscape" is attached (pls change to '*.crt'):

[eu10cpiotsap.txt](https://github.com/SAP/iot-starterkit/files/1614514/eu10cpiotsap.txt)

br,
fabian

**Comment by fableh** [comment]
Hi Anton,

sorry my mistake.
Problem is fixed by using this CA [cert](https://github.com/SAP/iot-starterkit/blob/master/cf/samples/curl-samples/send-measure-mqtt/eu10cpiotsap.crt).

br,
fabian
